### ISSUE TITLE
Why I can't hear any tick sound?

### ISSUE THREAD

**Issue by starock** [jamorat/iOS-asymetric-rhythm-metronome#1]
First of all, thanks for your fantastic code. And I'm waitting for your response. :)

**Comment by jamorat** [comment]
Hello, and thanks for your interest!  Will you be contributing some code to make this even better? I hope so!

As for why you can't hear any tick sound, I am not sure. Please let me know:
- What version of XCode are you using?
- Have you run this in the simulator, or also on a device?
- If you have run it on a device, what kind of device? What version device / version iOS?  Please tell me what you can about the device.

And of course the usuals: try restarting the device, ensuring the volume is turned up, and that you are upgraded to the latest versions.

Thanks!
Jack

**Comment by starock** [comment]
Oh~ It works on iPhone! :D  Perfect~

**Comment by jamorat** [comment]
Great! :dancer:  I look forward to any contributions you can make.  Peace. :D
